### ISSUE TITLE
Error - when running out of the box

### ISSUE THREAD

**Issue by shaharhalutz** [learnapollo/pokedex-react-native-exponent#3]
am having trouble running solution 5, out of the box: 
after pasting my projectID in the URI , (state/apollo.js) 
I run the app and the error in the XDE console shows:

Error in observer.next 
componentWillReceiveProps@http://packager.h3-k3x.shaharhalutz.exercise-05-solution.exp.direct:80/main.bundle?platform=ios&dev=true&strict=false&minify=false&hot=false&assetPlugin=exponent/tools/hashAssetFiles:121022:533 
measureLifeCyclePerf@http://packager.h3-k3x.shaharhalutz.exercise-05-solution.exp.direct:80/main.bundle?platform=ios&dev=true&strict=false&minify=false&hot=false&assetPlugin=exponent/tools/hashAssetFiles:18231:10 
updateComponent@http://packager.h3-k3x.shaharhalutz.exercise-05-solution.exp.direct:80/main.bundle?platform=ios&dev=true&strict=false&minify=false&hot=false&assetPlugin=exponent/tools/hashAssetFiles:18764:21 
receiveComponent@http://packager.h3-k3x.shaharhalutz.exercise-05-solution.exp.direct:80/main.bundle?platform=ios&dev=true&strict=false&minify=false&hot=false&assetPlugin=exponent/tools/hashAssetFiles:18701:21 
receiveComponent@http://packager.h3-k3x.shaharhalutz.exercise-05-solution.exp.direct:80/main.bundle?platform=ios&dev=true&strict=false&minify=false&hot=false&assetPlugin=exponent/tools/hashAssetFiles:16876:34 
_updateRenderedComponent@http://packager.h3-k3x.shaharhalutz.exercise-05-solution.exp.direct:80/main.bundle?platform=ios&dev=true&strict=false&minify=false&hot=false&assetPlugin=exponent/tools/hashAssetFiles:18908:33 
_performComponentUpdate@http://packager.h3-k3x.shaharhalutz.exercise-05-solution.exp.direct:80/main.bundle?platform=ios&dev=true&strict=false&minify=false&hot=false&assetPlugin=exponent/tools/hashAssetFiles:18878:30 
updateComponent@http://packager.h3-k3x.shaharhalutz.exercise-05-solution.exp.direct:80/main.bundle?platform=ios&dev=true&strict=false&minify=false&hot=false&assetPlugin=exponent/tools/hashAssetFiles:18799:29 
receiveComponent@http://packager.h3-k3x.shaharhalutz.exercise-05-solution.exp.direct:80/main.bundle?platform=ios&dev=true&strict=false&minify=false&hot=false&assetPlugin=exponent/tools/hashAssetFiles:18701:21 
receiveComponent@http://packager.h3-k3x.shaharhalutz.exercise-05-solution.exp.direct:80/main.bundle?platform=ios&dev=true&strict=false&minify=false&hot=false&assetPlugin=exponent/tools/hashAssetFiles:16876:34 
_updateRenderedComponent@http://packager.h3-k3x.shaharhalutz.exercise-05-solution.exp.direct:80/main.bundle?platform=ios&dev=true&strict=false&minify=false&hot=false&assetPlugin=exponent/tools/hashAssetFiles:18908:33 
_performComponentUpdate@http://packager.h3-k3x.shaharhalutz.exercise-05-solution.exp.direct:80/main.bundle?platform=ios&dev=true&strict=false&minify=false&hot=false&assetPlugin=exponent/tools/hashAssetFiles:18878:30 
updateComponent@http://packager.h3-k3x.shaharhalutz.exercise-05-solution.exp.direct:80/main.bundle?platform=ios&dev=true&strict=false&minify=false&hot=false&assetPlugin=exponent/tools/hashAssetFiles:18799:29 
performUpdateIfNecessary@http://packager.h3-k3x.shaharhalutz.exercise-05-solution.exp.direct:80/main.bundle?platform=ios&dev=true&strict=false&minify=false&hot=false&assetPlugin=exponent/tools/hashAssetFiles:18715:21 
performUpdateIfNecessary@http://packager.h3-k3x.shaharhalutz.exercise-05-solution.exp.direct:80/main.bundle?platform=ios&dev=true&strict=false&minify=false&hot=false&assetPlugin=exponent/tools/hashAssetFiles:16908:42 
runBatchedUpdates@http://packager.h3-k3x.shaharhalutz.exercise-05-solution.exp.direct:80/main.bundle?platform=ios&dev=true&strict=false&minify=false&hot=false&assetPlugin=exponent/tools/hashAssetFiles:16519:41 
perform@http://packager.h3-k3x.shaharhalutz.exercise-05-solution.exp.direct:80/main.bundle?platform=ios&dev=true&strict=false&minify=false&hot=false&assetPlugin=exponent/tools/hashAssetFiles:17255:16 
perform@http://packager.h3-k3x.shaharhalutz.exercise-05-solution.exp.direct:80/main.bundle?platform=ios&dev=true&strict=false&minify=false&hot=false&assetPlugin=exponent/tools/hashAssetFiles:17255:16 
flushBatchedUpdates@http://packager.h3-k3x.shaharhalutz.exercise-05-solution.exp.direct:80/main.bundle?platform=ios&dev=true&strict=false&minify=false&hot=false&assetPlugin=exponent/tools/hashAssetFiles:16541:20 
flushBatchedUpdates@[native code] 
closeAll@http://packager.h3-k3x.shaharhalutz.exercise-05-solution.exp.direct:80/main.bundle?platform=ios&dev=true&strict=false&minify=false&hot=false&assetPlugin=exponent/tools/hashAssetFiles:17321:19 
perform@http://packager.h3-k3x.shaharhalutz.exercise-05-solution.exp.direct:80/main.bundle?platform=ios&dev=true&strict=false&minify=false&hot=false&assetPlugin=exponent/tools/hashAssetFiles:17268:14 
batchedUpdates@http://packager.h3-k3x.shaharhalutz.exercise-05-solution.exp.direct:80/main.bundle?platform=ios&dev=true&strict=false&minify=false&hot=false&assetPlugin=exponent/tools/hashAssetFiles:38195:20 
enqueueUpdate@http://packager.h3-k3x.shaharhalutz.exercise-05-solution.exp.direct:80/main.bundle?platform=ios&dev=true&strict=false&minify=false&hot=false&assetPlugin=exponent/tools/hashAssetFiles:16569:32 
enqueueUpdate@http://packager.h3-k3x.shaharhalutz.exercise-05-solution.exp.direct:80/main.bundle?platform=ios&dev=true&strict=false&minify=false&hot=false&assetPlugin=exponent/tools/hashAssetFiles:32732:27 
enqueueSetState@http://packager.h3-k3x.shaharhalutz.exercise-05-solution.exp.direct:80/main.bundle?platform=ios&dev=true&strict=false&minify=false&hot=false&assetPlugin=exponent/tools/hashAssetFiles:32917:14 
setState@http://packager.h3-k3x.shaharhalutz.exercise-05-solution.exp.direct:80/main.bundle?platform=ios&dev=true&strict=false&minify=false&hot=false&assetPlugin=exponent/tools/hashAssetFiles:9364:29 
forceRenderChildren@http://packager.h3-k3x.shaharhalutz.exercise-05-solution.exp.direct:80/main.bundle?platform=ios&dev=true&strict=false&minify=false&hot=false&assetPlugin=exponent/tools/hashAssetFiles:114405:14 
next@http://packager.h3-k3x.shaharhalutz.exercise-05-solution.exp.direct:80/main.bundle?platform=ios&dev=true&strict=false&minify=false&hot=false&assetPlugin=exponent/tools/hashAssetFiles:114388:26 
http://packager.h3-k3x.shaharhalutz.exercise-05-solution.exp.direct:80/main.bundle?platform=ios&dev=true&strict=false&minify=false&hot=false&assetPlugin=exponent/tools/hashAssetFiles:118856:9 
forEach@[native code] 
next@http://packager.h3-k3x.shaharhalutz.exercise-05-solution.exp.direct:80/main.bundle?platform=ios&dev=true&strict=false&minify=false&hot=false&assetPlugin=exponent/tools/hashAssetFiles:118854:24 
http://packager.h3-k3x.shaharhalutz.exercise-05-solution.exp.direct:80/main.bundle?platform=ios&dev=true&strict=false&minify=false&hot=false&assetPlugin=exponent/tools/hashAssetFiles:119149:14 
http://packager.h3-k3x.shaharhalutz.exercise-05-solution.exp.direct:80/main.bundle?platform=ios&dev=true&strict=false&minify=false&hot=false&assetPlugin=exponent/tools/hashAssetFiles:119600:9 
forEach@[native code] 
http://packager.h3-k3x.shaharhalutz.exercise-05-solution.exp.direct:80/main.bundle?platform=ios&dev=true&strict=false&minify=false&hot=false&assetPlugin=exponent/tools/hashAssetFiles:119597:18 
http://packager.h3-k3x.shaharhalutz.exercise-05-solution.exp.direct:80/main.bundle?platform=ios&dev=true&strict=false&minify=false&hot=false&assetPlugin=exponent/tools/hashAssetFiles:115624:12 
baseForOwn@http://packager.h3-k3x.shaharhalutz.exercise-05-solution.exp.direct:80/main.bundle?platform=ios&dev=true&strict=false&minify=false&hot=false&assetPlugin=exponent/tools/hashAssetFiles:115586:23 
forOwn@http://packager.h3-k3x.shaharhalutz.exercise-05-solution.exp.direct:80/main.bundle?platform=ios&dev=true&strict=false&minify=false&hot=false&assetPlugin=exponent/tools/hashAssetFiles:119677:26 
broadcastQueries@http://packager.h3-k3x.shaharhalutz.exercise-05-solution.exp.direct:80/main.bundle?platform=ios&dev=true&strict=false&minify=false&hot=false&assetPlugin=exponent/tools/hashAssetFiles:119595:7 
broadcastNewStore@http://packager.h3-k3x.shaharhalutz.exercise-05-solution.exp.direct:80/main.bundle?platform=ios&dev=true&strict=false&minify=false&hot=false&assetPlugin=exponent/tools/hashAssetFiles:119032:22 
http://packager.h3-k3x.shaharhalutz.exercise-05-solution.exp.direct:80/main.bundle?platform=ios&dev=true&strict=false&minify=false&hot=false&assetPlugin=exponent/tools/hashAssetFiles:120444:37 
http://packager.h3-k3x.shaharhalutz.exercise-05-solution.exp.direct:80/main.bundle?platform=ios&dev=true&strict=false&minify=false&hot=false&assetPlugin=exponent/tools/hashAssetFiles:119522:21 
tryCallOne@http://packager.h3-k3x.shaharhalutz.exercise-05-solution.exp.direct:80/main.bundle?platform=ios&dev=true&strict=false&minify=false&hot=false&assetPlugin=exponent/tools/hashAssetFiles:30589:10 
http://packager.h3-k3x.shaharhalutz.exercise-05-solution.exp.direct:80/main.bundle?platform=ios&dev=true&strict=false&minify=false&hot=false&assetPlugin=exponent/tools/hashAssetFiles:30675:19 
callTimer@http://packager.h3-k3x.shaharhalutz.exercise-05-solution.exp.direct:80/main.bundle?platform=ios&dev=true&strict=false&minify=false&hot=false&assetPlugin=exponent/tools/hashAssetFiles:4164:9 
callImmediatesPass@http://packager.h3-k3x.shaharhalutz.exercise-05-solution.exp.direct:80/main.bundle?platform=ios&dev=true&strict=false&minify=false&hot=false&assetPlugin=exponent/tools/hashAssetFiles:4268:28 
callImmediates@http://packager.h3-k3x.shaharhalutz.exercise-05-solution.exp.direct:80/main.bundle?platform=ios&dev=true&strict=false&minify=false&hot=false&assetPlugin=exponent/tools/hashAssetFiles:4283:43 
guard@http://packager.h3-k3x.shaharhalutz.exercise-05-solution.exp.direct:80/main.bundle?platform=ios&dev=true&strict=false&minify=false&hot=false&assetPlugin=exponent/tools/hashAssetFiles:3805:3 
__callImmediates@http://packager.h3-k3x.shaharhalutz.exercise-05-solution.exp.direct:80/main.bundle?platform=ios&dev=true&strict=false&minify=false&hot=false&assetPlugin=exponent/tools/hashAssetFiles:3973:6 
http://packager.h3-k3x.shaharhalutz.exercise-05-solution.exp.direct:80/main.bundle?platform=ios&dev=true&strict=false&minify=false&hot=false&assetPlugin=exponent/tools/hashAssetFiles:3868:23 
guard@http://packager.h3-k3x.shaharhalutz.exercise-05-solution.exp.direct:80/main.bundle?platform=ios&dev=true&strict=false&minify=false&hot=false&assetPlugin=exponent/tools/hashAssetFiles:3805:3 
callFunctionReturnFlushedQueue@http://packager.h3-k3x.shaharhalutz.exercise-05-solution.exp.direct:80/main.bundle?platform=ios&dev=true&strict=false&minify=false&hot=false&assetPlugin=exponent/tools/hashAssetFiles:3866:6 
callFunctionReturnFlushedQueue@[native code]

**Comment by shaharhalutz** [comment]
this is no issue, was due to not inserting the Trainer Name in the gql query.

**Comment by tychota** [comment]
Cool that you have manage to resolve your issue. Don't hesitate to ask if you beed some help / explanation.
